#' viz_matrix2dendrogram
#'
#' @name viz_matrix2dendrogram
#' @param distmat a square matrix of cosine dist values generated by 'dist_matrix' function
#' @return a plot of a dendrogram
#' @export viz_matrix2dendrogram

viz_matrix2dendrogram <- function(distmat) {
  return(distmat)
  #Runs viz_kmeans_clustersize takes optimal K value uses to cut dendrogram tree
}
