#' viz_kmeans_clustersize
#'
#' @name viz_kmeans_clustersize
#' @param distmat a square matrix of cosine dist values generated by 'dist_matrix' function
#' @param k.max maximum number of clusters to evaluate default is 15
#' @param nboot number of bootstrap samples to determine gap statistic, default is 150
#' @importFrom cluster clusGap
#' @importFrom cluster maxSE
#' @importFrom stats kmeans
#' @return optimal_k an integer (K) representing optimal cluster size for distance matrix by gap statistic
#' @export viz_kmeans_clustersize

viz_kmeans_clustersize <- function(distmat, k.max = 15, nboot = 150) {

  # Calculate gap statistic
  gap_stat <- cluster::clusGap(
    distmat, FUN = kmeans, K.max = k.max, B = nboot)

  # Extract optimal K (using Tibshirani's 1-SE method)
  optimal_k <- cluster::maxSE(
    gap_stat$Tab[, "gap"],
    gap_stat$Tab[, "SE.sim"],
    method = "Tibs2001SEmax")

  return(optimal_k)
}
