---
title: 'SemanticDistance: An R package for Computing Semantic Distance in Structured Texts and Visualizing Clustering Properties in Unstructured Word Lists'

tags:
  - R
  - psychology
  - semantic memory
  - natural language processing
  - linguistics

authors:
  - name: Jamie Reilly
    orcid: 0000-0002-0891-438X
    equal-contrib: false
    corresponding: true
    affiliation: "1, 2"  # Ensure multiple affiliations are quoted

  - name: Emily B. Myers
    orcid: 0000-0002-9475-764X
    equal-contrib: false
    corresponding: false
    affiliation: "3, 4"

  - name: Hannah Mechtenberg
    orcid: 0000-0003-1436-1846
    equal-contrib: false
    corresponding: false
    affiliation: "4"

  - name: Jonathan E. Peelle
    orcid: 0000-0001-9194-854X
    equal-contrib: false
    corresponding: false
    affiliation: "5, 6, 7"

affiliations:
  - name: Department of Communication Sciences and Disorders, Temple University, United States
    index: 1

  - name: Department of Psychology and Neuroscience, Temple University, United States
    index: 2

  - name: Department of Speech, Language, and Hearing Sciences, University of Connecticut, United States
    index: 3

  - name: Department of Psychological Sciences, University of Connecticut, United States
    index: 4

  - name: Institute for Cognitive and Brain Health, Northeastern University, United States
    index: 5

  - name: Department of Communication Sciences and Disorders, Northeastern University, United States
    index: 6

  - name: Department of Psychology, Northeastern University, United States
    index: 7

date: 20 January 2026
funding: |
  R01 DC013063, R01 DC013064, R01 DC019507 (NIH NIDCD)
output: rticles::joss_article
bibliography: paper.bib
---

# Summary
 `SemanticDistance` computes pairwise distance between units of language (e.g., word-to-word, ngram-to-word, turn-to-turn) in both structured language samples and unstructured word lists. `SemanticDistance` has cleaning and formatting options including stopword removal and lemmatization. The package computes two complementary cosine distance indices for each pairwise contrast of interest. `SemanticDistance` can also be used to examine clustering properties within unstructured word lists, generating dendrograms and simple igraph network plots.  
 
# Software Design
 `SemanticDistance` was is an open-source R package designed to accommodate a wide range of user expertise (e.g., neuroscience, linguistics, computer science). The software does not leverage artificial intelligence or use any proprietary dependencies. The package instead indexes an internal lookup database containing publicly available lexical norms.

# Statment of need
`SemanticDistance` is unique in its capacity to compute semantic distance metrics within running language samples (e.g., word-to-word, bigram-to-word) and to produce semantic network visualizations. The package also provides complementary (but different) semantic distance metrics (experiential vs. embedding) computed over the same stimuli. This package will support novel insights into the flow of meaning within naturalistic language samples.

# Research Impact Statement
 `SemanticDistance` has supported one peer-reviewed publication to date in the journal, `Cortex` [@Mechtenberg:2026] along with one refereed conference presentation at the annual conference of the Society for the Neurobiology of Language. Importantly, the application enables a variety of analyses that have been formerly difficult or impossible, including comparing semantic distance measures with other measure of prediction in language, including those generated by large language models. \newline
 
# Description
Semantic distance has been broadly defined an empirical measure of conceptual relatedness between two or more words situated within an n-dimensional space [@Reilly:2025]. Semantic spaces differ in their dimensionality and biological plausibility. As an R package, `SemanticDistance` bundles text cleaning and formatting options (e.g., stopword removal, lemmatization) with two  two complementary semantic distance metrics that characterize/quantify similarity between pairs of language constituents (e.g., words, ngrams, turns). `CosDist_Glo` reflects cosine distance between vectors derived from training a GLOVE word embedding model [@Pennington:2014]. `CosDist_SD15` refects cosine distances derived from a 15 dimension sensorimotor and affective space derived from explicit human ratings [@Reilly:2023]. \newline

`SemanticDistance` computes indices of relatedness between lexical constituents within the following text formats:
1: **monologues**: stories, narratives, and structured text \newline
2: **dialogues**: turn-to-turn within two-person conversation transcripts. \newline
3: **word pairs in columns**:  word pairs \newline
4: **unordered lists**: bags-of-words  \newline

One of the most innovative functions of `SemanticDistance` is its capacity to generate rolling measures of semantic distance within stories or narratives with chunk sizes (e.g., word-to-word, turn-to-turn). Chunk size is an optional argument for many of the software's functions. For example, if a user specified a chunk or n-gram size of 5 words, the software would automatically compute a rollinhg measure of semantic distance betweem each new word in a language sample relative to the five words that preceded it. 

# AI Usage
`SemanticDistance` uses an internal database composed of many words with a fixed set of embeddings. The software does not use AI or rely on proprietary package dependencies. We did use GPT 4.0 (OpenAI) to troubleshoot R coding errors and assist with generating complex regular expressions (regex) used for cleaning text data. 

# References

